### PR TITLE
Overhaul build and install script

### PR DESCRIPTION
**Pull request by compor**
- Allow parameterization of build and installation
- Fortify script against errors
- Update repo gitignore for build dirs as created by aforementioned changes

This relates to: https://github.com/systems-nuts/UnASL/issues/53

### CODE REVIEW

**Comment by compor** [comment]
@blackgeorge-boom please have a quick look; any feedback welcome

**Review by blackgeorge-boom — COMMENTED** [review]
This looks good already! Abstracting the common functionality and parameterizing the directories is very useful! Thanks a lot.

**Comment by compor** [comment]
Added a few more fail checks and fixed a bug in determining destination location.
I think it's ready for now.

**Review by blackgeorge-boom — APPROVED** [review]
Looks great! Thanks a lot.

**Pull request merged**
